book-fetishes/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
	resources :reviews
  end
  root "books#index" # this is the home page for now
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

book-fetishes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

book-fetishes/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_attached_file :book_img, styles: { book_index: "250x350>", book_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

book-fetishes/app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

book-fetishes/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :book
	belongs_to :user
end

book-fetishes/app/models/user.rb
class User < ApplicationRecord
  has_many :books
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

book-fetishes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

book-fetishes/app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :find_book, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!, only: [:new, :edit]

  def index
     if params[:category].blank?
         @books = Book.all.order("created_at DESC")
     else 
	 @category_id = Category.find_by(name: params[:category]).id
         @books = Book.where(:category_id => @category_id).order("created_at DESC")
     end
  end

  def new
     @book = current_user.books.build
     @categories = Category.all.map{ |c| [c.name, c.id]}
  end
  
  def show
     if @book.reviews.blank?
	@average_review = 0
     else
	@average_review = @book.reviews.average(:rating).round(2)
     end
  end
     

  def create
     @book = current_user.books.build(book_params)
     @book.category_id = params[:category_id]
     if @book.save 
        redirect_to root_path
     else
        render 'new'
     end
  end
  
  def edit
     @categories = Category.all.map{ |c| [c.name, c.id]}
     
  end
  
  def update
     @book.category_id = params[:category_id]
     if @book.update(book_params)
        redirect_to book_path(@book)
     else
        render 'edit'
     end  
  end
  
  def destroy
     @book.destroy
     redirect_to root_path

  end

  private
	def book_params
        params.require(:book).permit(:title, :description, :author, :category_id, :book_img)
	end
    
    def find_book
        @book =  Book.find(params[:id])
    end
end

book-fetishes/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit, :update, :destroy]
        before_action :authenticate_user!, only: [:new , :edit]
	def new
		@review = Review.new
	end
	
	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id
		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end
	end
	
	def destroy
		@review.destroy
		redirect_to book_path(@book)
	end

	private
		def review_params
			params.require(:review).permit(:rating, :comment)
		end

		def find_book
			@book = Book.find(params[:book_id])	
		end
		
		def find_review
			@review = Review.find(params[:id])
		end
end

book-fetishes/app/helpers/application_helper.rb
module ApplicationHelper
end

book-fetishes/app/helpers/books_helper.rb
module BooksHelper
end

book-fetishes/app/helpers/reviews_helper.rb
module ReviewsHelper
end

book-fetishes/app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt =>"Select a category") %>
  <%= f.file_field :book_img %>
  <%= f.input :title, label:"Book Title"%>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

book-fetishes/app/views/books/edit.html.erb
<h1>Edit book</h1>

<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
  <%= f.select :category_id, @categories %>
  <%= f.file_field :book_img %>
  <%= f.input :title, label:"Book Title"%>
  <%= f.input :description %>
  <%= f.input :author %>
  <%= f.button :submit %>
<% end %>

book-fetishes/app/views/books/home.html.erb
<html>
<head>
<title> Department of Computer Science, DTU</title>
 <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <link rel="stylesheet" href="sign.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
  <script type="text/javascript" src="angular.min.js"></script>
  <script type="text/javascript" src="sign.js"> </script>
<link rel="stylesheet" href="css/style.css"/>
<link href='http://fonts.googleapis.com/css?family=Wellfleet' rel='stylesheet' type='text/css'>

 <link href='http://fonts.googleapis.com/css?family=Wellfleet' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Arvo:400,700,400italic,700italic' rel='stylesheet' type='text/css'> 
 <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Goudy+Bookletter+1911' rel='stylesheet' type='text/css'>
 

<style>
.scroll{
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  margin-left:-5px;
 
  font: normal 100%/normal Arial, Helvetica, sans-serif;
  color: rgba(999,999,999,0);
  text-align: center;
  min-height: 25%;
    height: 25%;
 
   width:100%;

   background-color:#1abc9c;
   border-radius: 10% 10% 10% 10%;

   margin-bottom: 18px;
  -o-text-overflow: clip;
  text-overflow: clip;
 -webkit-transition:all 2s;
    transition: all 2s;
  padding:10%;
z-index:2;

}
.scroll:hover{ height: 50%;
               color: rgba(999,999,999,1);}
</style>
<script>

$(document).ready(function() {

$('a[href*=#]').each(function() {
if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'')
&amp;amp;&amp;amp; location.hostname == this.hostname
&amp;amp;&amp;amp; this.hash.replace(/#/,'') ) {
var $targetId = $(this.hash), $targetAnchor = $('[name=' + this.hash.slice(1) +']');
var $target = $targetId.length ? $targetId : $targetAnchor.length ? $targetAnchor : false;
if ($target) {
var targetOffset = $target.offset().top;
$(this).click(function() {
$("#nav li a").removeClass("active");
$(this).addClass('active');
$('html, body').animate({scrollTop: targetOffset}, 1000);
return false;
});
}
}
});

});</script>


</head>
<body>


<div class="container-fluid" style="margin:20px">

  <div class="row content" id="slide1">
   
    <div class="col-sm-12" style="background-color:rgba(0,0,0,0);padding-top:100px ">
<!--
     <div class="col-sm-3"><div class="scroll">About Us</div></div>
     <div class="col-sm-3"><div class="scroll">Book Blog</div></div>
     <div class="col-sm-3"><div class="scroll">Services</div></div>
     <div class="col-sm-3"><div class="scroll">Contact Us</div>--><div class="jumbotron">
    <h1>Book Fetishes</h1>
    <p>One stop heaven for book lovers across the country.</p></div>


        <div class="col-sm-2"><div class="scroll">Home</div></div>
        <div class="col-sm-2"><div class="scroll">About Us</div></div>
         <div class="col-sm-2"> <div class="scroll">Book Blog</div></div>
       <div class="col-sm-2"> <div class="scroll">Services</div></div>
        <div class="col-sm-2"><div class="scroll">Contact Us</div></div>
    <div class="col-sm-2"><div class="scroll">Contact Us</div></div>
   
</div></div>
   
<!--
 <div class="content">

 <div id="christmas_tree"> </div>
 <div id="snowflakes1"></div>
 <div id="snowflakes2"></div>
 <h2>MERRY</h2>
 <h1>CHRISTMAS</h1>
 <div id="divider"> </div>
 <h3>HAPPY NEW YEAR </h3>
 <div id="ribbon"></div>
 <div id="new_year"> </div>
 </div> -->

 <div id="slide2">
 
 <div class="quotes_container">
<!--here the contect of about us goes, I hope you can do this yourself-->
<!--
 <h3 class="quotes">“Then the Grinch thought of something he hadn't before! What if Christmas, he thought, doesn't come from a store. What if Christmas...perhaps...means a little bit more!”</h3>
 <img src="images/gem-01.gif" align="left"/> <h4 class="author_name_gray">Dr. Seuss </h4>-->
 </div> 
 </div> 

 <div id="slide3">

 <div class="quotes_container">
<!--here the contect of book blog goes, I hope you can do this yourself-->
<!--
 <h3 class="quotes">“I truly believe that if we keep telling the Christmas story, singing the Christmas songs, and living the Christmas spirit, we can bring joy and happiness and peace to this world.” </h3>
 <img src="images/gem-02.gif" align="left"/> <h4 class="author_name_white">Norman Vincent Peale </h4>-->
 </div> 
 </div> 
  
 <div id="slide4">
 
 <div class="quotes_container">
<!--here the contect of services goes, I hope you can do this yourself-->
<!-- <h3 class="quotes">“Christmas doesn't come from a store, maybe Christmas perhaps means a little bit more....” </h3>
 <img src="images/gem-03.gif" align="left"/> <h4 class="author_name_gray">Dr. Seuss </h4>-->
 </div> 
 </div> 
 
 <div id="slide5">

 <div class="quotes_container">
<!--here the contect of contact us goes, I hope you can do this yourself-->
 <!--<h3 class="quotes">“My idea of Christmas, whether old-fashioned or modern, is very simple: loving others. Come to think of it, why do we have to wait for Christmas to do that?” </h3>
 <img src="images/gem-04.gif" align="left"/> <h4 class="author_name_white">Bob Hope </h4>-->
 
 </div> 
 </div> 
</body></html>

book-fetishes/app/views/books/index.html.erb
<h1 class="current-category"> <%= params[:category] %></h1> 
<% if @books.count == 0 %>
	<h1>There are no books currently in this category</h1>

<% else %>
	<div class="row">	
	<% @books.each do |book| %>
		<div class="col-md-3">
			<a href="/books/<%= book.id %>">
			  <%= image_tag book.book_img.url(:book_index), class: "book" %>
			</a>
		</div>
	<% end %>
	</div>
<% end %>

book-fetishes/app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

book-fetishes/app/views/books/show.html.erb
<div class="row">

	<div class="col-md-4">
		<%= image_tag @book.book_img.url(:book_show), class: "book-show" %>
	</div>
	<div class="col-md-4">
		<h2> <%= @book.title %> </h2>
		<h3> <%= @book.author %> </h3>
		<h2>Average Rating</h2>
		<div class="average-review-rating" data-score=<%= @average_review %>></div>
		<span>Based on <%= @book.reviews.count %> reviews</span> 
		<p> <%= @book.description %> </p>
	</div>
</div>

<div class="row">
	<%= render @book.reviews %>
	<div class="col-md-4">
		<%= link_to "Add Review", new_book_review_path(@book) %>
	</div>
</div>

<%= link_to "Back", root_path %>
<% if user_signed_in? %>
	<% if  @book.user_id == current_user.id %>
		<%= link_to "Edit book", edit_book_path(@book) %>
		<%= link_to "Delete book", book_path(@book), method: :delete, data: {confirm: "Are you sure?"} %>
	<% end %>
<% end %>

<script>
	$('.review-rating').raty({
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		},
		path: '/assets/'
	});
</script>

<script>
	$('.average-review-rating').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score')
		}
	});
</script>

book-fetishes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookFetishes</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
<!--
<nav class="navbar navbar-inverse headercss">

    <div class="navbar-header" style="padding:10px">
      <%= link_to "Book Fetishes" , root_path, class:"navbar-brand" %>
    </div>
    
    <div style="padding:10px; float:right" >
    <button type="button" class="btn btn-success btn-lg" > <%= link_to "Sign Up", new_user_registration_path %></button>
    <% if  user_signed_in? %>
     <button type="button" class="btn btn-info btn-lg" > <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></button>
     <% else %>
    <button type="button" class="btn btn-info btn-lg" ><%= link_to "Login ", new_user_session_path %></button>
    <% end %>
</div>
     
</nav>-->
	<nav class="navbar navbar-inverse">

		<div class="container">

			<div class="navbar-header">
				<%= link_to "Book Fetishes", root_path, class: "navbar-brand" %>
			</div>

			<ul class="nav navbar-nav">

                               <li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<% Category.all.each do |category| %>
							<li class="<%= 'active' if params[:category] == category.name %>">
								<%= link_to category.name, books_path(category: category.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				</li>


				<% if user_signed_in? %>
					<li><%= link_to "Add Book", new_book_path %></li>
				<% end %>

			</ul>

			<ul class="nav navbar-nav navbar-right">
                          <li><%= link_to "Sign Up", new_user_registration_path %></li>
			    <% if  user_signed_in? %>
			     <li> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			     <% else %>
			    <li><%= link_to "Login ", new_user_session_path %></l1>
			    <% end %>
				<!--<li><%= link_to "Sign Up", new_user_registration_path %></li>
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>	
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>-->
				
				
			</ul>

		</div>

	</nav>



    <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <div class="container">
	    <%= yield %>
    </div>
  </body>
</html>

book-fetishes/app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

book-fetishes/app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in? %>
	<% if current_user.id == review.user_id  %>
		<%= link_to "Edit", edit_book_review_path(review.book, review) %>
		<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: {confirm: "Are you sure?"} %>
	<% end %>
<% end %>

book-fetishes/app/views/reviews/edit.html.erb
<H1>Edit Review</H1>

<%= simple_form_for([@book, @review]) do |f| %>
	<div id="rating-form">
		<label>Rating</label>
	</div>
	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

book-fetishes/app/views/reviews/new.html.erb
<H1>New Review</H1>

<%= render 'form' %>